#!/bin/bash
date_time=`date +%Y%m%d_%H%M%S`
file_path=var/dumps
file_name=${file_path}/dump_${date_time}${db_name}.sql
host=db
database=db
log () {
    time=$(date --rfc-3339=seconds)
    echo "[$time] $1"
}

echo "MySQLdump" && echo

mkdir -p $file_path && chmod 777 -R $file_path
log "Dumping MySQL database '${database}'..." && echo
mysqldump -u root -proot -h $host $database > $file_name
echo && log "Done. Output file: '${file_name}'"

exit 0
