#!/bin/bash
file_name=$1
host=db
database=db
log () {
    time=$(date --rfc-3339=seconds)
    echo "[$time] $1"
}

echo "MySQLrestore" && echo

set -e
if [ $# -ne 1 ]; then
  echo && echo 1>&2 "  Usage: $(basename $0) <FILE>" && echo
  exit 1
fi

log "Restoring MySQL database '${database}'..." && echo
pv $file_name | mysql -u root -proot -h $host $database
echo && log "Done."

exit 0
